name: Nightly-for-Windows-YYC
on: 
  # push: #Uncomment this line to run the workflow on push
  workflow_dispatch: #This line allows you to run the workflow manually from the GitHub Actions page
  # workflow_call: #This line allows you to run the workflow from another workflow
jobs:
  build:
    name: Build and Release a Nightly version
    runs-on: windows-2022
    steps:
      # Check out the repository with the GameMaker project
      - uses: actions/checkout@v4
        with:
          lfs: true
      # Update the version.json file with build date and other versioning information
      - name: Set date-time and version info
        shell: pwsh
        run: |
          # Generate current date-time directly in the format you want
          $date_time = (Get-Date).ToString("yyyy-MM-dd-HHmm")
          echo "date_time=$date_time" >> $env:GITHUB_ENV
          
          # Set the version number (this could be dynamic or hardcoded)
          $Version = "Development"
          $BuildDate = $date_time
          $CommitHash = git rev-parse --short HEAD
      
          # Create the version.json content
          $VersionJson = @{
            version     = $Version
            build_date  = $BuildDate
            commit_hash = $CommitHash
          } | ConvertTo-Json
      
          # Write the version.json to disk
          Set-Content -Path datafiles/main/version.json -Value $VersionJson
          
      - id: gamemaker_build
        name: Build
        uses: ./.github/workflows/gamemaker_build.yml
        with:
          suffix: ${{ needs.checkout.outputs.yyp-path }}
          
      - name: Check if a nightly release exists
        id: check_nightly
        run: |
          gh release view nightly --repo ${{ github.repository }}
          if [ $? -eq 0 ] ; then
            echo "release_exists=true" >> $GITHUB_OUTPUT;
          else
            echo "release_exists=false" >> $GITHUB_OUTPUT;
          fi
        shell: bash
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - id: delete_release_tag
        name: Delete the existing nightly tag and release
        if: steps.check_nightly.outputs.release_exists
        run: |
          gh release delete nightly -y --cleanup-tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - id: create_release
        name: Create a Pre-Release and Upload the build
        uses: softprops/action-gh-release@v2.0.9
        with:
          name: ChapterMaster ${{ env.date_time }}
          tag_name: nightly
          prerelease: true
          generate_release_notes: true
          make_latest: true
          files: |
            ${{ steps.gamemaker_build.outputs.built_file }}/*
