name: Build GameMaker Project
on:
  workflow_call:
    inputs:
      yyc:
        required: false
        type: boolean
        default: false
      development:
        required: false
        type: boolean
        default: true
    outputs:
      built_file:
        value: ${{ jobs.build.outputs.built_file }}
      suffix:
        value: ${{ jobs.build.outputs.build_time }}
jobs:
  build:
    name: Build
    runs-on: windows-2022
    outputs:
      built_file: ${{ steps.igor_build.outputs.out-dir }}
      suffix: ${{ steps.date_time.outputs.date_time }}
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Set date-time and version info
        id: version_info
        shell: pwsh
        run: |
          # Generate current date-time directly in the format you want
          $date_time = (Get-Date).ToString("yyyy-MM-dd-HHmm")
          
          # Set the version number (this could be dynamic or hardcoded)
          $Version = "1.0.0"  # You can change this version to be dynamic if needed
          $BuildDate = $date_time
          $CommitHash = git rev-parse --short HEAD
          
          # Set outputs for version, build date, and commit hash
          echo "::set-output name=version::$Version"
          echo "::set-output name=build_date::$BuildDate"
          echo "::set-output name=commit_hash::$CommitHash"
      # This step finds the yyp file in the repository and saves the path to an output
      - id: find_yyp
        name: Find The yyp File
        run: |
          # Search for .yyp file recursively in the repository
          $yyp = Get-ChildItem -Path ${{ github.workspace }} -Recurse -Filter *.yyp
          
          # Check if the file was found
          if ($yyp.Count -eq 0) {
          Write-Error "No .yyp file found in the repository"
          exit 1
          }
          # If found, output the path of the .yyp file
          Write-Output "YYP file found at: $yyp"
          "yyp-path=$yyp" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          
      # This step sets up the GameMaker build CLI tool Igor https://github.com/bscotch/igor-setup
      - id: igor_setup
        name: Setup Igor
        uses: bscotch/igor-setup@v1.1.0
        with:
          runtime-version: 2023.11.1.160
          target-yyp: ${{ steps.find_yyp.outputs.yyp-path }}
          access-key: ${{ secrets.ACCESS_KEY }}
      # Update the version.json file with build date and other versioning information
      - id: igor_build
        name: Build with Igor
        uses: bscotch/igor-build@v1.0.3
        with:
          yyp-path: ${{ steps.find_yyp.outputs.yyp-path }}
          user-dir: ${{ steps.igor_setup.outputs.user-dir }}
          name: ChapterMaster-${{ inputs.development && inputs.development == 'true' && steps.date_time.outputs.date_time || steps.date_time.outputs.version }}-Windows.zip
          yyc: ${{ inputs.yyc }}
