name: Format Code

on:
  pull_request:
    types:
      - opened
      - edited
      - ready_for_review
      - synchronize

jobs:
  format:
    runs-on: ubuntu-latest  # Or 'windows-latest' if using Windows runner

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Download Release
        run: |
          curl -LO https://github.com/Pizzaandy/Gobo/releases/download/v0.4.0/gobo-ubuntu.zip

      - name: Extract ZIP
        run: |
          unzip gobo-ubuntu.zip

      - name: Ensure executable permissions
        run: |
          chmod +x ./gobo

      - name: Get Changed Files
        id: changed_files
        run: |
          changed_files=$(git diff --name-only origin/main...HEAD | grep '\.rs$' || true)
          echo "changed_files=$changed_files" >> $GITHUB_ENV

      - name: Run Formatter on Changed Files
        run: |
          if [ -n "$changed_files" ]; then
            for file in $changed_files; do
              ./gobo $file
            done
          else
            echo "No files changed, skipping formatting."
          fi

      - name: Clean up Gobo Files
        run: |
          rm -rf gobo-ubuntu.zip gobo

      - name: Check for formatting changes
        run: |
          git diff --exit-code || exit 1
